### ISSUE TITLE
Weekly changeset dump incorrectly flagging all changesets as closed

### ISSUE THREAD

**Issue by ToeBee** [openstreetmap/planetdump#1]
Opened this in trac but was redirected here.

All changesets in the weekly changeset dump file are marked as being closed even if they are still open at the time of the dump. 

 After talking about it in #osm-dev, TomH determined that it is because the now() function in the SQL on line 235 of  [planet06_pg.cpp](https://github.com/openstreetmap/planetdump/blob/master/planet06_pg.cpp#L235) returns server local time whereas the closed_at column is stored in UTC. Since closed_at is set to one hour in the future every time a changeset is updated, that comparison will always return false. 

 A possible fix is to change "now()" to "now() at time zone 'utc' "

**Comment by tomhughes** [comment]
Fixed in e406711139b9eb8db9d32fa4094325ec3841082c.
